name: ${project.name}
version: ${project.version}
description: 'SethBling''s ''The Building Game'' - optimized for Bukkit!'
depend: [WorldEdit, WorldGuard]
softdepend: []
author: Stealth2800
website: http://stealthyone.com
main: com.stealthyone.mcb.thebuildinggame.TheBuildingGame
commands:
  thebuildinggame:
    description: 'Base plugin command'
    aliases: [bg, tbg, buildinggame]